server:
  port: 8082


spring:
  application:
    name: chatservice
  kafka:
    bootstrap-servers: ${spring.environment.production.host}:9092

    consumer:
      group-id: game-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  environment:
    local:
      host: 192.168.0.2
      port: 6379
      password: ssafy
    stage:
      host: 3.37.1.251
      port: 6379
      password: ssafy
    production:
      host: i6c209.p.ssafy.io
      port: 6379
      password: $$jae923009$
    redis:
      host: 13.125.149.219
      port: 6379
      password: ssafy
