version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - /redis/data:/var/lib/redis
      - /redis/log:/var/log/redis

  connection-status-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka